/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import buisness.Person;
import buisness.Address;
import buisness.CheckingAccount;
import buisness.DriversLicense;
import buisness.MedicalRecord;
import buisness.SavingAccount;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import static userinterface.DriversLicenseJPanel.resize;

public class CreateUserJPanel extends javax.swing.JPanel {
        private Person person;
    	private Address address = new Address();
	private CheckingAccount checkingAccount = new CheckingAccount();
	private SavingAccount savingAccount = new SavingAccount();
	private DriversLicense driversLicense = new DriversLicense();
	private MedicalRecord medicalRecord = new MedicalRecord();
	
	private TitleJPanel titleJPanel;
        private DemographicInfoJPanel demographicInfoJPanel;
	private AddressJPanel addressJPanel;
	private CheckingAccountJPanel checkingAccountJPanel;
	private DriversLicenseJPanel driversLicenseJPanel;
	private MedicalRecordJPanel medicalRecordJPanel;
	private SavingAccountJPanel savingAccountJPanel;
        
    /**
     * Creates new form CreateUserJPanel
     */
    public CreateUserJPanel(Person person) {
        initComponents();
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

        this.person = person;
        
        titleJPanel = new TitleJPanel();
        demographicInfoJPanel = new DemographicInfoJPanel();
	addressJPanel = new AddressJPanel();
	checkingAccountJPanel = new CheckingAccountJPanel();
	driversLicenseJPanel = new DriversLicenseJPanel(driversLicense);
        driversLicenseJPanel.setDisplayLicense(false);
	medicalRecordJPanel = new MedicalRecordJPanel();
	savingAccountJPanel = new SavingAccountJPanel();
        
        this.add(medicalRecordJPanel,0);
        this.add(driversLicenseJPanel,0);
        this.add(checkingAccountJPanel,0);
        this.add(savingAccountJPanel,0);
        this.add(addressJPanel,0);
        this.add(demographicInfoJPanel,0);
        this.add(titleJPanel,0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitUserBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 241, 184));

        submitUserBtn.setBackground(new java.awt.Color(161, 139, 128));
        submitUserBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        submitUserBtn.setText("Create Profile");
        submitUserBtn.setPreferredSize(new java.awt.Dimension(300, 20));
        submitUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(submitUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submitUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUserBtnActionPerformed
        // TODO add your handling code here:
        person.setFirstName(demographicInfoJPanel.getFirstNameTxtField().getText());
        person.setLastName(demographicInfoJPanel.getLastNameTxtField().getText());
        person.setPhoneNumber(demographicInfoJPanel.getPhoneNumberTxtField().getText());
        person.setDateOfBirth(demographicInfoJPanel.getDateOfBirthTxtField().getText());
        person.setAge(demographicInfoJPanel.getAgeTxtField().getText());
        person.setHeight(demographicInfoJPanel.getHeightTxtField().getText());
        person.setWeight(demographicInfoJPanel.getWeightTxtField().getText());
        person.setSocialSecurityNo(demographicInfoJPanel.getSocialSecurityNumberTxtField().getText());

        address.setCity(addressJPanel.getCityTxtField().getText());
        address.setState(addressJPanel.getStateTxtField().getText());
        address.setStreetAddress(addressJPanel.getStreetAddressTxtField().getText());
        address.setZipCode(addressJPanel.getZipCodeTxtField().getText());

        person.setAddress(address);

        checkingAccount.setAccountBalance(checkingAccountJPanel.getAccountBalanceTxtField().getText());
        checkingAccount.setAccountType(checkingAccountJPanel.getAccountTypeTxtField().getText());
        checkingAccount.setBankAccountNumber(checkingAccountJPanel.getAccountNumberTxtField().getText());
        checkingAccount.setBankName(checkingAccountJPanel.getBankNameTxtField().getText());
        checkingAccount.setBankRoutingNumber(checkingAccountJPanel.getRoutingNumberTxtField().getText());

        person.setCheckingAccount(checkingAccount);

        savingAccount.setAccountBalance(savingAccountJPanel.getAccountBalanceTxtField().getText());
        savingAccount.setAccountType(savingAccountJPanel.getAccountTypeTxtField().getText());
        savingAccount.setBankAccountNumber(savingAccountJPanel.getAccountNumberTxtField().getText());
        savingAccount.setBankName(savingAccountJPanel.getBankNameTxtField().getText());
        savingAccount.setBankRoutingNumber(savingAccountJPanel.getRoutingNumberTxtField().getText());

        person.setSavingAccount(savingAccount);

        driversLicense.setBloodType(driversLicenseJPanel.getBloodTypeTxtField().getText());
        driversLicense.setDateOfExpiration(driversLicenseJPanel.getDateOfExpirationTxtField().getText());
        driversLicense.setDateOfIssue(driversLicenseJPanel.getDateOfIssueTxtField().getText());
        driversLicense.setLicenseNumber(driversLicenseJPanel.getLicenseNumberTxtField().getText());
        person.setDriversLicense(driversLicense);

        medicalRecord.setMedicalRecordNumber(medicalRecordJPanel.getMedicalRecordNumberTxtField().getText());
        medicalRecord.setAlergy1(medicalRecordJPanel.getAlergy1TxtField().getText());
        medicalRecord.setAlergy2(medicalRecordJPanel.getAlergy2TxtField().getText());
        medicalRecord.setAlergy3(medicalRecordJPanel.getAlergy3TxtField().getText());

        person.setMedicalRecord(medicalRecord);

        JOptionPane.showMessageDialog(null, "Created User Successfully!");
    }//GEN-LAST:event_submitUserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton submitUserBtn;
    // End of variables declaration//GEN-END:variables
}
