/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import buisness.Person;
import buisness.DriversLicense;
import java.awt.image.BufferedImage;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileSystemView;


public class DriversLicenseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriversLicenseJPanel
     */
    
    private DriversLicense driversLicense;
    //private BufferedImage driversLicense1;
    
    private boolean displayLicense;

    public boolean isDisplayLicense() {
        return displayLicense;
    }

    public void setDisplayLicense(boolean displayLicense) {
        this.displayLicense = displayLicense;
    }
    
    

    public JButton getAddDriverLicenseImg() {
        return addDriverLicenseImg;
    }

//    public void setAddDriverLicenseImg(JButton addDriverLicense) {
//        this.addDriverLicenseImg = addDriverLicense;
//    }
//
//    public BufferedImage getDriversLicense1() {
//        return driversLicense1;
//    }
//
//    public void setDriversLicense1(BufferedImage driversLicense) {
//        this.driversLicense1 = driversLicense;
//    }
    
    public DriversLicenseJPanel(DriversLicense driversLicense) {
        initComponents();
        this.driversLicense = driversLicense;
    }

    public JTextField getBloodTypeTxtField() {
        return bloodTypeTxtField;
    }

    public void setBloodTypeTxtField(JTextField bloodTypeTxtField) {
        this.bloodTypeTxtField = bloodTypeTxtField;
    }

    public JTextField getDateOfExpirationTxtField() {
        return dateOfExpirationTxtField;
    }

    public void setDateOfExpirationTxtField(JTextField dateOfExpirationTxtField) {
        this.dateOfExpirationTxtField = dateOfExpirationTxtField;
    }

    public JTextField getDateOfIssueTxtField() {
        return dateOfIssueTxtField;
    }

    public void setDateOfIssueTxtField(JTextField dateOfIssueTxtField) {
        this.dateOfIssueTxtField = dateOfIssueTxtField;
    }

    public JTextField getLicenseNumberTxtField() {
        return licenseNumberTxtField;
    }

    public void setLicenseNumberTxtField(JTextField licenseNumberTxtField) {
        this.licenseNumberTxtField = licenseNumberTxtField;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        licenseNumberTxtField = new javax.swing.JTextField();
        dateOfIssueTxtField = new javax.swing.JTextField();
        bloodTypeTxtField = new javax.swing.JTextField();
        dateOfExpirationTxtField = new javax.swing.JTextField();
        addDriverLicenseImg = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 241, 184));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("5.Drivers License Information");

        jLabel2.setText("License Number:");

        jLabel3.setText("Date of Issue:");

        jLabel4.setText("Blood Type:");

        jLabel5.setText("Date of Expiration:");

        licenseNumberTxtField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        dateOfIssueTxtField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        bloodTypeTxtField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        dateOfExpirationTxtField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        addDriverLicenseImg.setBackground(new java.awt.Color(161, 139, 128));
        addDriverLicenseImg.setText("Add Drivers License");
        addDriverLicenseImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDriverLicenseImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(licenseNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateOfIssueTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateOfExpirationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bloodTypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(addDriverLicenseImg, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(licenseNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dateOfIssueTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(bloodTypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateOfExpirationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDriverLicenseImg))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDriverLicenseImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriverLicenseImgActionPerformed

        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView());
        j.showSaveDialog(null); 
        File driverLicenseFile = j.getSelectedFile();
        BufferedImage driverLicenseImage;
        
        try {
            driverLicenseImage = ImageIO.read(driverLicenseFile);
            driversLicense.setDriversLicenseImage(resize(driverLicenseImage,200, 100));
        } catch (IOException ex) {
            System.out.println("Failed to upload drivers license!");
        }
            //System.out.println(driverLicenseImage);
           
        // TODO add your handling code here:
    }//GEN-LAST:event_addDriverLicenseImgActionPerformed
    
    @Override
    protected void paintComponent(Graphics g) {
        
        super.paintComponent(g);
        try{
            if(displayLicense) {
                addDriverLicenseImg.setVisible(false);
                g.drawImage(driversLicense.getDriversLicenseImage(), 800, 50, this);
            } 
        }
        catch(Exception e){
            addDriverLicenseImg.setVisible(false);
            System.out.println("No image uploaded");
        }
        
    }
    
    // reference: https://memorynotfound.com/java-resize-image-fixed-width-height-example/
    public static BufferedImage resize(BufferedImage img, int newW, int newH) { 
        Image tmp = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
        BufferedImage dimg = new BufferedImage(newW, newH, BufferedImage.TYPE_INT_ARGB);

        Graphics2D g2d = dimg.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();

        return dimg;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDriverLicenseImg;
    private javax.swing.JTextField bloodTypeTxtField;
    private javax.swing.JTextField dateOfExpirationTxtField;
    private javax.swing.JTextField dateOfIssueTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField licenseNumberTxtField;
    // End of variables declaration//GEN-END:variables
}
