

package userinterface.RestaurantAdminRole;


import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    Restaurant restaurant;
    DB4OUtil dB4OUtil;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = dB4OUtil.retrieveSystem("resadmin");
        this.dB4OUtil = dB4OUtil;
        for(Restaurant r : this.ecoSystem.getRestaurantDirectory().getRestaurants()){
            if(r.getRestaurantAdmin().getUser().getName().equals(userAccount.getUser().getName())){
                this.restaurant = r;
                break;
            }
        }
        populate(restaurant);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageRestaurantInfo = new javax.swing.JButton();
        btnManageMenu = new javax.swing.JButton();
        btnManageOrders = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        lblResturantNanme = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnManageRestaurantInfo.setText("Manage Restaurant Info");
        btnManageRestaurantInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRestaurantInfoActionPerformed(evt);
            }
        });
        add(btnManageRestaurantInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, -1));

        btnManageMenu.setText("Manage menu");
        btnManageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMenuActionPerformed(evt);
            }
        });
        add(btnManageMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, -1));

        btnManageOrders.setText("Manage Orders");
        btnManageOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrdersActionPerformed(evt);
            }
        });
        add(btnManageOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Restaurant :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        lblResturantNanme.setText("<value>");
        add(lblResturantNanme, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageRestaurantInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRestaurantInfoActionPerformed
        // TODO add your handling code here:
        JPanel manageRestaurantInfoJPanel = new ManageRestaurantInfoJPanel(userProcessContainer,dB4OUtil,restaurant);
        userProcessContainer.add("manageRestaurantInfo",manageRestaurantInfoJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(this.userProcessContainer);
        
    }//GEN-LAST:event_btnManageRestaurantInfoActionPerformed

    private void btnManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMenuActionPerformed
        JPanel manageMenu = new ManageMenuJPanel(userProcessContainer,dB4OUtil,restaurant);
        userProcessContainer.add("ManageMenu",manageMenu);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnManageMenuActionPerformed

    private void btnManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrdersActionPerformed
        JPanel manageOrdersJPanel = new ManageOrdersJPanel(userProcessContainer,dB4OUtil,restaurant);
        userProcessContainer.add("ManageOrders",manageOrdersJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(this.userProcessContainer);
    }//GEN-LAST:event_btnManageOrdersActionPerformed
    public  void populate(Restaurant r){
        this.restaurant = r;
        lblResturantNanme.setText(this.restaurant.getName());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageMenu;
    private javax.swing.JButton btnManageOrders;
    private javax.swing.JButton btnManageRestaurantInfo;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResturantNanme;
    // End of variables declaration//GEN-END:variables
    
}
