/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Role.AdminRole;
import Business.User.User;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author akhil
 */
public class AddRestuarantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddRestuarant
     */   
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private DB4OUtil dB4OUtil;
    public AddRestuarantJPanel(JPanel userProcessContainer,DB4OUtil dB4OUtil) {
        initComponents();     
        this.userProcessContainer=userProcessContainer;
        this.dB4OUtil = dB4OUtil;
        this.ecosystem= dB4OUtil.retrieveSystem("add resturat panel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtResturantName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtManagerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtManagerUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtManagerPassword = new javax.swing.JTextField();
        btnAddResturant = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Resturant Name");

        txtResturantName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResturantNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Manager Name");

        txtManagerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManagerNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Manager Username");

        txtManagerUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManagerUsernameActionPerformed(evt);
            }
        });

        jLabel4.setText("Manager Password");

        txtManagerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManagerPasswordActionPerformed(evt);
            }
        });

        btnAddResturant.setText("Add Resturant");
        btnAddResturant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddResturantActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(28, 28, 28)
                            .addComponent(txtManagerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(28, 28, 28)
                            .addComponent(txtManagerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(28, 28, 28)
                            .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(28, 28, 28)
                            .addComponent(txtResturantName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnAddResturant))
                    .addComponent(btnBack))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtResturantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtManagerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtManagerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddResturant)
                .addGap(0, 96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtResturantNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResturantNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResturantNameActionPerformed

    private void txtManagerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManagerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManagerNameActionPerformed

    private void txtManagerUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManagerUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManagerUsernameActionPerformed

    private void txtManagerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManagerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManagerPasswordActionPerformed

    private void btnAddResturantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddResturantActionPerformed
        // TODO add your handling code here:
        if(txtResturantName.getText().isEmpty()){            
            JOptionPane.showMessageDialog(null,"Please enter restuarant name!");
            return;
        }
        if(txtManagerName.getText().isEmpty()){      
            JOptionPane.showMessageDialog(null,"Please enter manager name!");
            return;
        }
        if(txtManagerUsername.getText().isEmpty()){      
            JOptionPane.showMessageDialog(null,"Please enter manager username!");
            return;
        }
        for(Restaurant r: this.ecosystem.getRestaurantDirectory().getRestaurants()){
            if(r.getRestaurantAdmin().getUsername().equals(txtManagerUsername.getText())){
                JOptionPane.showMessageDialog(null, "Username exists! Enter different username");
                return;
            }
        }
        if(txtManagerPassword.getText().isEmpty()){      
            JOptionPane.showMessageDialog(null,"Please enter manager password!");
            return;
        }
        User user = ecosystem.getUserDirectory().createUser(txtManagerName.getText()); //employee name
        
        UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(txtManagerUsername.getText(),txtManagerPassword.getText() , user, new AdminRole());
        
        Restaurant res = ecosystem.getRestaurantDirectory().createRestaurant(null,txtResturantName.getText() , userAccount);
        
        dB4OUtil.storeSystem(ecosystem);
        JOptionPane.showMessageDialog(null,"Resturant created successfully!");
        txtManagerName.setText("");
        txtManagerPassword.setText("");
        txtManagerUsername.setText("");
        txtResturantName.setText("");
        return;
        
    }//GEN-LAST:event_btnAddResturantActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) this.userProcessContainer.getLayout();
        Component [] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageRestuarantsJPanel){
                ManageRestuarantsJPanel mrjp =(ManageRestuarantsJPanel) comp;
                mrjp.populate();
            }
        }
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddResturant;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtManagerPassword;
    private javax.swing.JTextField txtManagerUsername;
    private javax.swing.JTextField txtResturantName;
    // End of variables declaration//GEN-END:variables
}
